# File is used for local development and testing purposes only. Secrets and sensitive information is handled in GitHub Actions when deployed to AWS.

services:
  postgres:
    image: postgres:16
    container_name: sudokubury-postgres
    environment:
      - POSTGRES_DB=SudokuGameAppDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyStrongPassword123#
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sudokubury-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 60s

  sudokubury-app:
    image: boogsdev/sudokubury-webapp:latest
    container_name: sudokubury-app
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=SudokuGameAppDb;Username=postgres;Password=MyStrongPassword123#
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=88b86ee56165de42cfb5cc65b616159672e5348c1dddb754f74114df54b91264
      - Jwt__Issuer=SudokuburyApp
      - Jwt__Audience=SudokuburyApp
      - Jwt__ExpireDays=7
      - AllowedOrigins__0=http://localhost:8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sudokubury-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  sudokubury-network:
    driver: bridge